### ISSUE TITLE
Transparent proxy'ing

### ISSUE THREAD

**Issue by JANorman** [elazarl/goproxy#88] opened 2015-02-02 16:35 UTC
Hi,

I'm implementing a transparent proxy that will behave as a filter to HTTP traffic that's coming into a web application. The plan is that as HTTP traffic enters on port `4567`, it should get redirected to port `8080` (the proxy), where the request headers are scanned, and then given everything is healthy, the request is released back to the Sinatra app exposed on `4567`

I've previously implemented this using [MITMProxy](http://mitmproxy.org/) and it's transparent mode (which has been working). I've been using the following IP tables to pipe the traffic through the proxy first.

````
sudo iptables -t nat -I INPUT 1 -m tcp -p tcp --dport 4567 -j RETURN
sudo iptables -t nat -A PREROUTING -m tcp -p tcp --dport 4567 -j REDIRECT --to-ports 8080
````

Today I installed GoProxy since I'm drawn to the fact it's just a simple proxy.

I followed the main instructions for setting up the proxy (in the README.md) as well as tried to implement it using the transparent proxy example. 

Using a combination of the above iptables and the ones in the transparent proxy example didn't seem to to work. 

When using the above iptables, the proxy seemed to get stuck in an infinite loop, with the following (and more) being output:

````
2015/02/02 15:18:10 Server starting up! - configured to listen on http interface :8080 and https interface :3128
2015/02/02 15:18:15 [001] INFO: Got request /player/12 172.17.8.101:45000 GET /player/12
2015/02/02 15:18:15 [002] INFO: Got request /player/12 172.17.8.101:45000 GET http://172.17.8.101:45000/player/12
2015/02/02 15:18:15 [002] INFO: Sending request GET http://172.17.8.101:45000/player/12
2015/02/02 15:18:15 [003] INFO: Got request /player/12 172.17.8.101:45000 GET /player/12
2015/02/02 15:18:15 [004] INFO: Got request /player/12 172.17.8.101:45000 GET http://172.17.8.101:45000/player/12
2015/02/02 15:18:15 [004] INFO: Sending request GET http://172.17.8.101:45000/player/12
2015/02/02 15:18:15 [005] INFO: Got request /player/12 172.17.8.101:45000 GET /player/12
2015/02/02 15:18:15 [006] INFO: Got request /player/12 172.17.8.101:45000 GET http://172.17.8.101:45000/player/12
2015/02/02 15:18:15 [006] INFO: Sending request GET http://172.17.8.101:45000/player/12
2015/02/02 15:18:15 [007] INFO: Got request /player/12 172.17.8.101:45000 GET /player/12
2015/02/02 15:18:15 [008] INFO: Got request /player/12 172.17.8.101:45000 GET http://172.17.8.101:45000/player/12
2015/02/02 15:18:15 [008] INFO: Sending request GET http://172.17.8.101:45000/player/12
2015/02/02 15:18:15 [009] INFO: Got request /player/12 172.17.8.101:45000 GET /player/12
2015/02/02 15:18:15 [010] INFO: Got request /player/12 172.17.8.101:45000 GET http://172.17.8.101:45000/player/12
2015/02/02 15:18:15 [010] INFO: Sending request GET http://172.17.8.101:45000/player/12
2015/02/02 15:18:15 [011] INFO: Got request /player/12 172.17.8.101:45000 GET /player/12
2015/02/02 15:18:15 [012] INFO: Got request /player/12 172.17.8.101:45000 GET http://172.17.8.101:45000/player/12
2015/02/02 15:18:15 [012] INFO: Sending request GET http://172.17.8.101:45000/player/12
2015/02/02 15:18:15 [013] INFO: Got request /player/12 172.17.8.101:45000 GET /player/12
2015/02/02 15:18:15 [014] INFO: Got request /player/12 172.17.8.101:45000 GET http://172.17.8.101:45000/player/12
2015/02/02 15:18:15 [014] INFO: Sending request GET http://172.17.8.101:45000/player/12
2015/02/02 15:18:15 [015] INFO: Got request /player/12 172.17.8.101:45000 GET /player/12
2015/02/02 15:18:15 [016] INFO: Got request /player/12 172.17.8.101:45000 GET http://172.17.8.101:45000/player/12
2015/02/02 15:18:15 [016] INFO: Sending request GET http://172.17.8.101:45000/player/12
2015/02/02 15:18:15 [017] INFO: Got request /player/12 172.17.8.101:45000 GET /player/12
2015/02/02 15:18:15 [018] INFO: Got request /player/12 172.17.8.101:45000 GET http://172.17.8.101:45000/player/12
2015/02/02 15:18:15 [018] INFO: Sending request GET http://172.17.8.101:45000/player/12
2015/02/02 15:18:15 [019] INFO: Got request /player/12 172.17.8.101:45000 GET /player/12
2015/02/02 15:18:15 [020] INFO: Got request /player/12 172.17.8.101:45000 GET http://172.17.8.101:45000/player/12
2015/02/02 15:18:15 [020] INFO: Sending request GET http://172.17.8.101:45000/player/12
````

Note: this is being run inside a docker container, hence why the ports are different, but internally it's port `4567`

I've been using [this transparent proxy script](https://github.com/elazarl/goproxy/blob/master/examples/transparent/transparent.go).

Would you happen to know why this might not be working? If there's any other information I can provide, please let me know.

**Comment by mzimmerman** [comment] 2015-02-02 16:42
I'm the author of the particular example you're trying to use.

I'm having a little trouble understanding what you're trying to do, but the example you're using isn't a web application filter.  It doesn't "release" the request so much as it re-issues it to it's destination.  If the destination is local, then the IP tables rule may fire again which then the proxy's own request gets redirected again to the proxy and so on and so forth.  That may be what's happening here, but it's hard to tell.

Could you describe your use case more?  What criteria makes the request "healthy" ?

**Comment by JANorman** [comment] 2015-02-02 17:09
Thanks for getting back to me :+1: 

So the idea is that inside our docker container, when a request comes into it externally, the proxy will need to look at the Authorization header, match this against known credentials, and given it's correct, let the traffic continue internally to the application. When the authorization credentials don't match, we want to end the request there and return a 403. 

The problems I'm having at the moment isn't so much the credentials matching, but more that it's having problems allowing the request through to the application. As you've seen, it appears to be stuck in an infinite loop, more than likely caused by the IP table rules. 

I've also tried the example in the main README,https://github.com/elazarl/goproxy/blob/master/README.md#a-taste-of-goproxy (without the setting of the header), and that resulted in the message:
````
This is a proxy server. Does not respond to non-proxy requests
````

I am curious as to whether the same iptable rules that work for MITMProxy will work for GoProxy.

**Comment by mzimmerman** [comment] 2015-02-02 17:49
For this instance, you want to use it as what's called a reverse-proxy.  Instead of being closer to the client, you're closer to the server.  The difference being that when goproxy re-issues the request, it does so by terminating the tcp connection and opening a new one.  In your case, the new one is opened and *again* gets filtered by your iptables rules (which then gets handled by goproxy).  One way to avoid that would be to use an interface parameter to iptables, -i ethexternal so it only triggers on outside connections coming in and not the newly initiated goproxy connections.

**Comment by elazarl** [comment] 2015-04-07 19:53
Looks like the issue is resolved. I'm closing it. If there's still problem, do not hesitate to reopen.

**Closed by elazarl** 2015-04-07 19:53 UTC

**Comment by JANorman** [comment] 2015-04-07 21:29
Apologies for leaving it open. All resolved now.
