### ISSUE TITLE
Release versions for go package

### ISSUE THREAD

**Issue by JanneKiiskila** [elazarl/goproxy#496] opened 2023-01-31 08:23 UTC
The go package page; https://pkg.go.dev/github.com/elazarl/goproxy refers to [3 versions](https://pkg.go.dev/github.com/elazarl/goproxy?tab=versions), but they are all format `0.0 date-hash`. It would be nice, if the package could be released as a proper `v1.1.0` or similar (as for example [ginkgo](https://pkg.go.dev/github.com/onsi/ginkgo?tab=versions) or [gomega](https://pkg.go.dev/github.com/onsi/gomega?tab=versions) do).

Current tags are `v1.1` and `v1.0` - which `go.mod` apparently does like, as fetching those fails.

My guess would be that tagging them with semver -compatible tags v1.1.0 and v1.0.0 would do the trick already?

Ginkgo for example has the tags in that format (vMajor.Minor.Patch), see [Ginkgo tags](https://github.com/onsi/ginkgo/tags).

**Comment by jeffwidman** [comment] 2023-02-12 07:46
Duplicate of:
* https://github.com/elazarl/goproxy/issues/394

**Closed** 2023-02-12 13:55 UTC

**Comment by JanneKiiskila** [comment] 2023-02-12 13:57
Darn, I tried to look for a similar one befoere submitting this, but missed it.
Closed as dupe.
