### ISSUE TITLE
certificate problem with latest Firefox

### ISSUE THREAD

**Issue by tsgan** [elazarl/goproxy#109] opened 2015-06-03 04:41 UTC
When trying to connect to ssl site using Firefox:

2015/06/03 12:38:28 [093] INFO: Running 1 CONNECT handlers
2015/06/03 12:38:28 [093] INFO: on 0th handler: &{2 <nil> <nil> <nil>} www.google.mn:443
2015/06/03 12:38:28 [093] INFO: Assuming CONNECT is TLS, mitm proxying it
2015/06/03 12:38:28 [093] WARN: Cannot handshake client www.google.mn:443 remote error: bad certificate

On browser:

Secure Connection Failed

An error occurred during a connection to www.google.mn. security library: improperly formatted DER-encoded message. (Error code: sec_error_bad_der)

```
The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
Please contact the website owners to inform them of this problem.
```

**Comment by elazarl** [comment] 2015-06-03 04:50
@tsgan thanks.

Can you get the recevied certificate with `openssl s_client -show-cert` and paste it here?

**Comment by g3rk6** [comment] 2015-06-03 07:08
@elazarl 

Here you go.

CONNECTED(00000003)
depth=1 O = github.com/elazarl/goproxy, CN = github.com/elazarl/goproxy
verify error:num=19:self signed certificate in certificate chain
verify return:0
---
Certificate chain
 0 s:/O=GoProxy untrusted MITM proxy Inc
   i:/O=github.com/elazarl/goproxy/CN=github.com/elazarl/goproxy
-----BEGIN CERTIFICATE-----
MIICSjCCAbWgAwIBAgIVAMmxkKOAOwmV9l7WV9QJbJNfhEzAMAsGCSqGSIb3DQEB
CzBKMSMwIQYDVQQKExpnaXRodWIuY29tL2VsYXphcmwvZ29wcm94eTEjMCEGA1UE
AxMaZ2l0aHViLmNvbS9lbGF6YXJsL2dvcHJveHkwHhcNNzAwMTAxMDAwMDAwWhcN
NDkxMjMxMDAwMDAwWjArMSkwJwYDVQQKEyBHb1Byb3h5IHVudHJ1c3RlZCBNSVRN
IHByb3h5IEluYzCBnzANBgkqhkiG9w0BAQEFAAOBjQAwgYkCgYEA5pUCuwlcZET4
FurwUKbXeb3LgSB69PAlKMBI2Io4vIEp7EZj8Av4T3V+9FyxhI/foJlHavER37Ci
QOTqCH2C8IZoUO7OaM1TtYSQI3j2AeG2EVZayQXNvyQ42WWpkyc2e/S1Bt6/Sc46
5eHf7H5da3QPLWiQxLU/zapTu94EkQsCAwEAAaNPME0wDgYDVR0PAQH/BAQDAgCg
MBMGA1UdJQQMMAoGCCsGAQUFBwMBMAwGA1UdEwEB/wQCMAAwGAYDVR0RBBEwD4IN
d3d3Lmdvb2dsZS5tbjALBgkqhkiG9w0BAQsDgYEAAgAz3ftzF/gPVTpoEtoH3n3v
pxuN3qudg6jsUERMSqwn8Q98XPlQ7XmgNYEWye+HDeP/ZZWNw+MDH7QYqH4o5PCn
62qSEg2cID56lSZHg+XaHSyMcCRvcwXL9PU5Ly1tRP5KcnX6NaP0XPdZU+IDP33l
Uzs+WVdvGB9OqDlerL4=
-----END CERTIFICATE-----
 1 s:/O=github.com/elazarl/goproxy/CN=github.com/elazarl/goproxy
   i:/O=github.com/elazarl/goproxy/CN=github.com/elazarl/goproxy
-----BEGIN CERTIFICATE-----
MIICSjCCAbWgAwIBAgIBADALBgkqhkiG9w0BAQUwSjEjMCEGA1UEChMaZ2l0aHVi
LmNvbS9lbGF6YXJsL2dvcHJveHkxIzAhBgNVBAMTGmdpdGh1Yi5jb20vZWxhemFy
bC9nb3Byb3h5MB4XDTAwMDEwMTAwMDAwMFoXDTQ5MTIzMTIzNTk1OVowSjEjMCEG
A1UEChMaZ2l0aHViLmNvbS9lbGF6YXJsL2dvcHJveHkxIzAhBgNVBAMTGmdpdGh1
Yi5jb20vZWxhemFybC9nb3Byb3h5MIGdMAsGCSqGSIb3DQEBAQOBjQAwgYkCgYEA
vz9BbCaJjxs73Tvcq3leP32hAGerQ1RgvlZ68Z4nZmoVHfl+2Nr/m0dmW+GdOfpT
cs/KzfJjYGr/84x524fiuR8GdZ0HOtXJzyF5seoWnbBIuyr1PbEpgRhGQMqqOUuj
YExeLbfNHPIoJ8XZ1Vzyv3YxjbmjWA+S/uOe9HWtDbMCAwEAAaNGMEQwDgYDVR0P
AQH/BAQDAgCkMBMGA1UdJQQMMAoGCCsGAQUFBwMBMA8GA1UdEwEB/wQFMAMBAf8w
DAYDVR0RBAUwA4IBKjALBgkqhkiG9w0BAQUDgYEAIcL8huSmGMompNujsvePTUnM
oEUKtX4Eh/+s+DSfV/TyI0I+3GiPpLplEgFWuoBIJGios0r1dKh5N0TGjxX/RmGm
qo7E4jjJuo8Gs5U8/fgThZmshax2lwLtbRNwhvUVr65GdahLsZz8I+hySLuatVvR
qHHq/FQORIiNyNpq/Hg=
-----END CERTIFICATE-----
---
Server certificate
subject=/O=GoProxy untrusted MITM proxy Inc
issuer=/O=github.com/elazarl/goproxy/CN=github.com/elazarl/goproxy
---
No client certificate CA names sent
---
SSL handshake has read 1669 bytes and written 471 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES256-SHA
Server public key is 1024 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-SHA
    Session-ID: 03935828C44D8A222C9656E72BAA4AE6A9AC9A27496095453892C75115939ED7
    Session-ID-ctx:
    Master-Key: A15D212AA0BDD73A495C4150C3FC9445847C44B69FBD2A06011569B933245B4C46065A241AF055F35E810FAF8B7E2914
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket:
    0000 - 34 ba d8 6f 95 7d 96 2f-0c 5e d1 1c 09 b5 93 4e   4..o.}./.^.....N
    0010 - 66 03 d5 21 bf fa fe ef-52 ad 7d 81 89 98 0f 55   f..!....R.}....U
    0020 - 47 98 69 f8 43 47 55 ee-cd 84 91 83 cf d8 45 c1   G.i.CGU.......E.
    0030 - 14 f9 9b 15 e0 6f e7 3a-e2 ed 01 3f 07 96 d4 79   .....o.:...?...y
    0040 - d1 d7 0e 6a 74 98 5a 24-e5 ef df 47 bf 81 a1 b2   ...jt.Z$...G....
    0050 - 0e f7 e8 3b da 29 1f d7-4d 7b 53 99 2c 95 33 15   ...;.)..M{S.,.3.
    0060 - 93 48 b3 44 62 70 09 9e-                          .H.Dbp..

    Start Time: 1433315229
    Timeout   : 300 (sec)
    Verify return code: 19 (self signed certificate in certificate chain)
---

**Comment by tsgan** [comment] 2015-06-11 16:43
Looks like recent Firefox requires 2048 bit keys and it seems generating new certificate helps.

**Comment by elazarl** [comment] 2015-06-11 18:14
@tsgan, Thanks! Do you want to generate a new certificate, embed it with
goproxy's cert.go, and send a PR?

**Comment by g3rk6** [comment] 2015-06-21 20:10
@elazarl 
We've just confirmed that the key length doesn't have to be 2048 and 1024 works. Latest Mozilla NSS does strict DER checking, hence the error. In order to resolve the issue generate a new certificate with following command and replace the existing DER encoded cert and key in certs.go.

```openssl req -x509 -newkey rsa:1024 -keyout key.pem -out cert.pem -days 12775 -nodes```

**Comment by elazarl** [comment] 2015-07-22 18:28
Just letting everyone know that this is severe issue, and I intend to fix
it next week.

I apologize for the delay.

**Comment by ashmckenzie** [comment] 2016-07-16 15:02
Any movement on this?

**Comment by elazarl** [comment] 2016-07-19 04:48
Hi,
I apologize, would try to solve it in the next few days.

**Comment by ashmckenzie** [comment] 2016-07-19 05:14
If it's just a case of generating a new root cert, I'll create a PR?

**Comment by elazarl** [comment] 2016-07-19 05:15
Sure,
Just make sure it's a proper root cert, no SHA1, etc.

**Comment by ErikPelli** [comment] 2024-12-30 20:05
No updates about this issue and no one recently complained about issues with Firefox.
Closing this issue.
If the problem is still present, feel free to reopen it and let me know!

**Closed by ErikPelli** 2024-12-30 20:05 UTC
